const CARDS = { #Cost(0), Attack(1), Health(2), 
				#Card Type(3), Card Ability(4),
				#Lunge(5), Fury(6), Holy Shield(7),
				#Life Drain(8), Fast Hands(9), Momentum(10),
				#Bodyguard(11), Holy Blessing(12), Reincarnate(13),
				#Evasive(14), Ability Script(15)

	"Monk" : [1, 1, 1, 
	"Unit", "", 
	false, false, false,
	false, false, true,
	false, false, false,
	false],
	
	"Trainer" : [1, 2, 2, 
	"Unit", "Momentum", 
	false, false, false,
	false, false, true,
	false, false, false,
	false],
	
	"Guard" : [1, 2, 4, 
	"Unit", "Bodyguard", 
	false, false, false,
	false, false, false,
	true, false, false,
	false],
	
	"Priest" : [1, 1, 1, 
	"Unit", "Bodyguard", 
	false, false, false,
	false, false, false,
	false, true, false,
	false],
	
	"Skely" : [1, 2, 2, 
	"Unit", "Reincarnate", 
	false, false, false,
	false, false, false,
	false, false, true,
	false],
	
	"Knight" : [1, 2, 3, 
	"Unit", "Knight Ability", 
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Archer" : [2, 1, 1, 
	"Unit", "Archer Ability", 
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Demon" : [3, 5, 7, "Unit", 
	"Demon Ability", 
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Discovery" : [2, null, null, 
	"Spell", "Draw Cards", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/Discovery.gd"],
	
	"Holy Strike" : [2, null, null, 
	"Spell", "", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/HolyStrike.gd"],
	
	"Bottle of Devotion" : [0, null, null, 
	"Spell", "", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/BottleOfDevotion.gd"],
	
	"Fatigue Aura" : [2, null, null, 
	"Spell", "", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/FatigueAura.gd"],
	
	"Crusader's Might" : [3, null, null, 
	"Spell", "", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/CrusadersMight.gd"],
	
	"Defender Aura" : [3, null, null, 
	"Spell", "", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/Defender.gd"],
	
	"Paladin Defender" : [0, 3, 5, 
	"Unit", "", 
	false, false, false, 
	false, false, false,
	true, false, false,
	false],
	
	"Summon the Infantry" : [6, null, null, 
	"Spell", "", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/Infantry.gd"],
	
	"Knight 4" : [0, 4, 8, 
	"Unit", "", 
	false, false, false,
	false, false, false,
	true, false, false,
	false],

	"Knight 2" : [0, 2, 4, 
	"Unit", "", 
	false, false, false,
	false, false, false,
	true, false, false,
	false],

	"Knight 1" : [0, 1, 2, 
	"Unit", "", 
	false, false, false,
	false, false, false,
	true, false, false,
	false],
	
	"Training Student" : [1, 1, 1,
	"Unit", "",
	false, false, false,
	false, false, true,
	false, false, false,
	false],
	
	"Aggressive Youngin" : [1, 2, 1,
	"Unit", "",
	false, false, false,
	false, true, false,
	false, false, false,
	false],
	
	"Training Mentor" : [1, 1, 3,
	"Unit", "",
	false, false, false,
	false, false, false,
	false, false, false,
	false],

	"Aspirant Squire" : [1, 1, 1,
	"Unit", "",
	false, false, false,
	false, false, false,
	true, false, false,
	false],
	
	"Banner Bearer" : [3, 3, 3,
	"Unit", "",
	false, false, false,
	false, false, false,
	false, false, false,
	false],

	"Blessed Parishioner" : [2, 2, 2,
	"Unit", "",
	true, false, false,
	false, false, false,
	false, false, false,
	false],

	"Thaloran Lightguard" : [8, 7, 7,
	"Unit", "",
	false, false, false,
	false, false, false,
	false, false, false,
	false],

	"Artimose Aetherion" : [5, 2, 4,
	"Unit", "",
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Uther Pureheart" : [4, 4, 4,
	"Unit", "",
	false, false, false,
	false, false, true,
	false, false, false,
	false],

	"Holy Crusader" : [4, 3, 2,
	"Unit", "",
	false, true, true,
	false, false, false,
	true, false, false,
	false],

	"Blessed Crusader Hound" : [3, 1, 4,
	"Unit", "",
	false, false, false,
	false, false, false,
	false, false, true,
	false],

	"Way of Astral Master" : [8, 10, 10,
	"Unit", "",
	false, false, false,
	false, true, true,
	false, false, false,
	false],
	
	"Way of Open Hand Master" : [8, 10, 10,
	"Unit", "",
	false, false, false,
	false, true, true,
	false, false, false,
	false],

	"Kensei Monk" : [6, 6, 5,
	"Unit", "",
	false, true, false,
	false, true, true,
	false, false, false,
	false],
	
	"Bulwark Brother" : [2, 1, 3,
	"Unit", "Demon Ability",
	false, false, false,
	false, false, false,
	true, false, false,
	false],
	
	"Boulder" : [1, 0, 3,
	"Unit", "Demon Ability",
	false, false, false,
	false, false, false,
	true, false, false,
	false],

	"Way of Mercy Master" : [6, 5, 8,
	"Unit", "",
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Way of Drinking Master" : [4, 3, 9,
	"Unit", "",
	false, false, false,
	false, false, true,
	false, false, false,
	false],

	"Swiftfist Monk" : [5, 4, 4,
	"Unit", "Demon Ability",
	false, true, false,
	false, true, false,
	false, false, false,
	false],

	"Astral Projection" : [5, null, null,
	"Spell", "Draw Cards",
	false, false, false,
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/Discovery.gd"],

	"Shadow Arts" : [3, null, null,
	"Spell", "Deal 2 Damage to a random enemy",
	false, false, false,
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/FrozenSpike.gd"],
	
	"Cup of Chai" : [1, null, null, 
	"Spell", "Gain 1 Devotion", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/BottleOfDevotion.gd"],
}
