const CARDS = { #Cost(0), Attack(1), Health(2), 
				#Card Type(3), Card Ability(4),
				#Lunge(5), Fury(6), Holy Shield(7),
				#Life Drain(8), Fast Hands(9), Momentum(10),
				#Bodyguard(11), Holy Blessing(12), Reincarnate(13),
				#Evasive(14), Ability Script(15)

	"Monk" : [1, 3, 1, 
	"Unit", "Fast Hands", 
	false, false, false,
	false, true, false,
	false, false, false,
	false],
	
	"Trainer" : [1, 2, 2, 
	"Unit", "Momentum", 
	false, false, false,
	false, false, true,
	false, false, false,
	false],
	
	"Guard" : [1, 2, 4, 
	"Unit", "Bodyguard", 
	false, false, false,
	false, false, false,
	true, false, false,
	false],
	
	"Priest" : [1, 1, 1, 
	"Unit", "Bodyguard", 
	false, false, false,
	false, false, false,
	false, true, false,
	false],
	
	"Skely" : [1, 2, 2, 
	"Unit", "Reincarnate", 
	false, false, false,
	false, false, false,
	false, false, true,
	false],
	
	"Knight" : [1, 2, 3, 
	"Unit", "Knight Ability", 
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Archer" : [2, 1, 1, 
	"Unit", "Archer Ability", 
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Demon" : [3, 5, 7, "Unit", 
	"Demon Ability", 
	false, false, false,
	false, false, false,
	false, false, false,
	false],
	
	"Discovery" : [2, null, null, 
	"Spell", "Draw Cards", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/Discovery.gd"],
	
	"Holy Strike" : [2, null, null, 
	"Spell", "Deal 2 Damage to a target enemy, Streak: Gain a Bottle of Devotion", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/HolyStrike.gd"],
	
	"Bottle of Devotion" : [0, null, null, 
	"Spell", "Gain 1 Devotion", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/BottleOfDevotion.gd"],
	
	"Fatigue Aura" : [2, null, null, 
	"Spell", "Enemy player’s spell cards cost 1 more Devotion to play. Lasts 2 enemy turns.", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/FatigueAura.gd"],
	
	"Crusader's Might" : [3, null, null, 
	"Spell", "Deal 3 damage and draw a card.", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/CrusadersMight.gd"],
	
	"Defender Aura" : [3, null, null, 
	"Spell", "At the end of your turn, summon a 3/5 Paladin Defender. Lasts 3 turns.", 
	false, false, false, 
	false, false, false,
	false, false, false,
	false,
	"res://Scripts/Abilities/Defender.gd"],
	
	"Paladin Defender" : [0, 3, 5, 
	"Unit", "Bodyguard", 
	false, false, false, 
	false, false, true,
	false, false, false,
	false],
}
